// Base components for procedural name generation

// Japanese prefixes mapped to English equivalents
export const PREFIXES = {
  // Colors
  color: {
    ao: "blue",
    aka: "red",
    shiro: "white",
    kuro: "black",
    midori: "green",
    murasaki: "purple",
    kin: "golden",
    gin: "silver",
    hai: "ash",
    cha: "brown",
    momo: "pink",
    sora: "sky",
    ai: "indigo",
    kohaku: "amber",
    sango: "coral",
    suigyoku: "jade",
    benibana: "crimson",
    yamabuki: "gold-orange",
    wasurenagusa: "forget-me-not",
    fuji: "wisteria",
  },

  // Light and celestial
  light: {
    hikari: "light",
    kagayaki: "radiant",
    hotaru: "firefly",
    tsuki: "moon",
    hi: "sun",
    hoshi: "star",
    yoru: "night",
    akatsuki: "dawn",
    yuugure: "twilight",
    kasumi: "mist",
    kiri: "fog",
    niji: "rainbow",
    aurora: "aurora",
    ginga: "galaxy",
    tenku: "heavenly",
  },

  // Nature elements
  nature: {
    yama: "mountain",
    kawa: "river",
    umi: "sea",
    mori: "forest",
    sora: "sky",
    ishi: "stone",
    take: "bamboo",
    ki: "tree",
    hana: "flower",
    ha: "leaf",
    ne: "root",
    mi: "fruit",
    tsuyu: "dew",
    ame: "rain",
    yuki: "snow",
    kaze: "wind",
    nami: "wave",
    shima: "island",
    tani: "valley",
    mine: "peak",
    numa: "marsh",
    ike: "pond",
    taki: "waterfall",
  },

  // Qualities and feelings
  quality: {
    yume: "dream",
    shizuka: "quiet",
    yasashii: "gentle",
    tsuyoi: "strong",
    chiisai: "small",
    ookii: "large",
    karui: "light",
    omoi: "heavy",
    amaku: "sweet",
    nigai: "bitter",
    sawayaka: "fresh",
    odayaka: "calm",
    hisoka: "secret",
    komorebi: "dappled",
    seirei: "spirit",
    inochi: "life",
    nagomi: "harmony",
    yorokobi: "joy",
  },

  // Animals (cat-world appropriate)
  animal: {
    neko: "cat",
    tori: "bird",
    sakana: "fish",
    cho: "butterfly",
    kame: "turtle",
    usagi: "rabbit",
    tanuki: "raccoon",
    kitsune: "fox",
    tsuru: "crane",
    kumo: "spider",
    hotaru: "firefly",
    semi: "cicada",
    tonbo: "dragonfly",
    hachi: "bee",
    kaeru: "frog",
  },

  // Seasonal
  seasonal: {
    haru: "spring",
    natsu: "summer",
    aki: "autumn",
    fuyu: "winter",
    sakura: "cherry",
    momiji: "maple",
    ume: "plum",
    kiku: "chrysanthemum",
    botan: "peony",
    tsubaki: "camellia",
    ayame: "iris",
    suisen: "narcissus",
  },

  // Sacred and spiritual
  sacred: {
    kami: "divine",
    sei: "holy",
    shinsei: "sacred",
    reikon: "spirit",
    kiyome: "purifying",
    inori: "prayer",
    megumi: "blessing",
    ten: "heaven",
    shiawase: "bliss",
    yasuragi: "serenity",
  },

  // Magical and mystical
  mystical: {
    maho: "magic",
    fushigi: "mysterious",
    yogen: "prophecy",
    kiseki: "miracle",
    unmei: "fate",
    tamashii: "soul",
    mugen: "infinite",
    shinpi: "mystic",
    genso: "phantom",
    maboroshi: "illusion",
  },

  // Cave and underground
  underground: {
    ana: "cave",
    chika: "underground",
    kurayami: "darkness",
    iwaya: "grotto",
    dokutsu: "cavern",
    fukaku: "deep",
    kakure: "hidden",
    himitsu: "secret",
    shizumu: "sunken",
    nemuru: "sleeping",
  },

  // Fruit and sweet
  fruity: {
    kajitsu: "fruit",
    mi: "berry",
    amai: "sweet",
    jueki: "juice",
    nashi: "pear",
    ringo: "apple",
    mikan: "citrus",
    budou: "grape-like",
    ichigo: "strawberry",
    kaki: "persimmon",
  },

  // Cat-euphoric (catnip family)
  euphoric: {
    neko: "cat",
    yoi: "intoxicating",
    matatabi: "silvervine",
    shiawase: "blissful",
    yume: "dream",
    odori: "dancing",
    asobi: "playful",
    gokuraku: "paradise",
    utage: "festive",
    tanoshii: "joyful",
  },

  // Time and state
  temporal: {
    asahi: "morning-sun",
    yuuhi: "evening-sun",
    mayonaka: "midnight",
    tokiwa: "eternal",
    furui: "ancient",
    wakai: "young",
    nagai: "long",
    mijikai: "short",
    hayai: "swift",
    osoi: "slow",
  },
};

// Japanese suffixes for plant types
export const SUFFIXES = {
  // General plants
  general: {
    sou: "herb",
    kusa: "grass",
    bana: "flower",
    hana: "blossom",
    ki: "tree",
    no_ki: "tree-of",
    take: "bamboo",
    mo: "seaweed",
    ran: "orchid",
    tsuyu: "dew-plant",
    shida: "fern",
    koke: "moss",
    tsuta: "vine",
  },

  // Mushrooms/fungi
  fungi: {
    kinoko: "mushroom",
    take: "fungus",
    dake: "mushroom",
  },

  // Aquatic
  aquatic: {
    mo: "algae",
    ukikusa: "floating-plant",
    suiren: "water-lily",
    hasu: "lotus",
    kawa_no: "river",
    mizu: "water",
  },

  // Size modifiers
  size: {
    ko: "small",
    hime: "princess",
    oni: "giant",
    dai: "great",
    chou: "ultra",
  },

  // Location modifiers
  location: {
    yama: "mountain",
    mizu: "water",
    no: "field",
    hama: "beach",
    mine: "peak",
    tani: "valley",
  },
};

// Forms and growth patterns
export const FORMS = {
  tree: [
    "towering",
    "spreading",
    "weeping",
    "columnar",
    "gnarled",
    "graceful",
    "ancient",
    "twisted",
    "umbrella-shaped",
    "multi-trunked",
  ],
  shrub: [
    "bushy",
    "compact",
    "sprawling",
    "mounding",
    "upright",
    "rounded",
    "layered",
    "dense",
    "open",
    "cascading",
  ],
  herb: [
    "low-growing",
    "upright",
    "trailing",
    "rosette-forming",
    "clumping",
    "spreading",
    "creeping",
    "tufted",
    "mat-forming",
    "feathery",
  ],
  edible: [
    "leafy",
    "root-bearing",
    "fruiting",
    "grain-bearing",
    "pod-forming",
    "bulbous",
    "tuberous",
    "climbing",
    "bushy",
    "stalk-forming",
  ],
  medicinal: [
    "delicate",
    "robust",
    "aromatic",
    "bitter-leaved",
    "resinous",
    "succulent",
    "fibrous",
    "downy",
    "thorny",
    "woody",
  ],
  ornamental: [
    "elegant",
    "dramatic",
    "dainty",
    "sculptural",
    "architectural",
    "flowing",
    "symmetrical",
    "wild",
    "refined",
    "exotic",
  ],
  "glow-plant": [
    "ethereal",
    "luminous",
    "translucent",
    "crystalline",
    "wispy",
    "delicate",
    "spectral",
    "shimmering",
    "phosphorescent",
    "radiant",
  ],
  aquatic: [
    "floating",
    "submerged",
    "emergent",
    "ribbon-like",
    "feathery",
    "pad-forming",
    "trailing",
    "rooted",
    "free-floating",
    "mat-forming",
  ],
  fungi: [
    "clustered",
    "solitary",
    "shelf-forming",
    "cap-and-stem",
    "coral-like",
    "gelatinous",
    "puffball",
    "cup-shaped",
    "branching",
    "honeycomb",
  ],
  fruit: [
    "laden with berries",
    "heavy with fruit",
    "climbing fruiter",
    "bushy fruit-bearer",
    "trailing vine",
    "orchard standard",
    "dwarf fruiting",
    "espalier-trained",
    "wild bramble",
    "prolific producer",
  ],
  catnip: [
    "sprawling aromatic",
    "bushy euphoric",
    "creeping ground-cover",
    "upright stimulant",
    "feathery-leaved",
    "dense aromatic mound",
    "trailing vine",
    "compact container variety",
    "wild meadow form",
    "cultivated hybrid",
  ],
  cave: [
    "wall-clinging",
    "ceiling-hanging",
    "floor-creeping",
    "stalactite-like",
    "pale and ghostly",
    "root-like tendrils",
    "fungal-symbiotic",
    "crystal-encrusted",
    "thread-thin",
    "bioluminescent cluster",
  ],
  sacred: [
    "temple-trained",
    "altar-worthy",
    "meditation-inspiring",
    "ancient and gnarled",
    "perfectly symmetrical",
    "incense-producing",
    "prayer-offering form",
    "ceremonial standard",
    "sacred grove specimen",
    "shrine-guardian",
  ],
  magical: [
    "reality-bending",
    "phase-shifting",
    "fortune-touched",
    "spirit-attracting",
    "dream-inducing",
    "prophecy-revealing",
    "time-touched",
    "fate-woven",
    "soul-resonant",
    "enchantment-holding",
  ],
};

// Color palettes per category
export const COLOR_PALETTES = {
  warm: [
    "golden-yellow",
    "sunset-orange",
    "deep crimson",
    "warm amber",
    "russet brown",
    "coral pink",
    "honey gold",
    "persimmon orange",
    "wine red",
    "copper",
  ],
  cool: [
    "deep green",
    "forest emerald",
    "sea blue",
    "silver-gray",
    "lavender",
    "cool mint",
    "slate blue",
    "teal",
    "ice blue",
    "sage",
  ],
  earth: [
    "rich brown",
    "ochre",
    "terracotta",
    "olive",
    "moss green",
    "clay red",
    "umber",
    "sand",
    "bark brown",
    "loam",
  ],
  glow: [
    "pale moonlight",
    "soft blue-green",
    "ethereal white",
    "ghostly green",
    "golden shimmer",
    "violet luminescence",
    "pink phosphorescence",
    "amber glow",
    "silver radiance",
    "cyan light",
  ],
  neutral: [
    "cream",
    "ivory",
    "pearl",
    "charcoal",
    "dove gray",
    "bone white",
    "ash",
    "stone",
    "platinum",
    "pewter",
  ],
};

// Distinctive features by category
export const DISTINCTIVE_FEATURES = {
  tree: [
    "deeply furrowed bark",
    "smooth silvery trunk",
    "peeling bark in papery strips",
    "fragrant wood",
    "brilliant autumn color",
    "dense canopy",
    "exposed root system",
    "drooping branches",
    "spreading crown",
    "twisted limbs",
    "aromatic leaves",
    "ornamental fruit",
    "showy blossoms",
    "year-round foliage",
    "striking silhouette",
  ],
  shrub: [
    "dense foliage",
    "thorny stems",
    "variegated leaves",
    "aromatic when crushed",
    "showy flower clusters",
    "colorful berries",
    "evergreen leaves",
    "cascading branches",
    "compact growth",
    "layered branching",
    "textured bark",
    "autumn color display",
    "fragrant blooms",
    "sculptural form",
    "soft fuzzy leaves",
  ],
  herb: [
    "deeply lobed leaves",
    "feathery foliage",
    "silver-edged leaves",
    "purple-tinged stems",
    "aromatic oils",
    "tiny clustered flowers",
    "fuzzy leaf surface",
    "serrated leaf margins",
    "basal rosette",
    "hollow stems",
    "milky sap",
    "succulent leaves",
    "pungent scent",
    "delicate flower spikes",
    "runner-forming",
  ],
  edible: [
    "plump edible seeds",
    "tender young shoots",
    "sweet flesh",
    "crisp texture",
    "rich flavor",
    "nutritious roots",
    "abundant harvest",
    "long storage life",
    "versatile in cooking",
    "seasonal availability",
    "easy to cultivate",
    "high yield",
    "pest resistant",
    "quick growing",
    "heirloom variety",
  ],
  medicinal: [
    "bitter compounds",
    "soothing oils",
    "healing resin",
    "calming properties",
    "anti-inflammatory",
    "digestive aid",
    "wound healing",
    "fever reducing",
    "pain relieving",
    "sleep inducing",
    "energy boosting",
    "immune supporting",
    "detoxifying",
    "circulation improving",
    "respiratory clearing",
  ],
  ornamental: [
    "spectacular blooms",
    "year-round interest",
    "striking foliage",
    "architectural form",
    "cascading habit",
    "fragrant flowers",
    "attractive seedheads",
    "colorful stems",
    "variegated pattern",
    "unusual texture",
    "dramatic silhouette",
    "long bloom period",
    "cut flower quality",
    "pollinator attracting",
    "evening fragrance",
  ],
  "glow-plant": [
    "soft bioluminescence",
    "pulsing light",
    "moonlight responsive",
    "ethereal glow",
    "translucent tissues",
    "luminous veins",
    "glowing spores",
    "night-blooming",
    "light-storing",
    "dawn-fading glow",
    "touch-responsive light",
    "seasonal luminosity",
    "color-shifting glow",
    "steady radiance",
    "flickering light",
  ],
  aquatic: [
    "floating leaves",
    "submerged foliage",
    "water-purifying",
    "oxygen-producing",
    "fish-sheltering",
    "surface-covering",
    "deep-rooted",
    "current-resistant",
    "seasonal dormancy",
    "rapid spreading",
    "fragrant flowers above water",
    "decorative seedpods",
    "attractive underwater movement",
    "shade-providing",
    "erosion-preventing",
  ],
  fungi: [
    "delicate gills",
    "thick fleshy cap",
    "velvety texture",
    "ringed stem",
    "spore-releasing",
    "symbiotic with trees",
    "decomposer role",
    "seasonal fruiting",
    "distinctive aroma",
    "color-changing when cut",
    "woody texture",
    "gelatinous consistency",
    "clustered growth",
    "underground network",
    "quick appearance after rain",
  ],
  fruit: [
    "abundant sweet berries",
    "large juicy fruits",
    "clusters of small drupes",
    "single prized specimens",
    "edible skin and flesh",
    "aromatic when ripe",
    "color-changing ripeness",
    "long harvest season",
    "exceptional flavor",
    "high sugar content",
    "firm flesh for transport",
    "soft and delicate",
    "seeds easily saved",
    "self-pollinating variety",
    "requires partner plant",
  ],
  catnip: [
    "intoxicating aroma",
    "euphoria-inducing oils",
    "irresistible to felines",
    "rolling-behavior trigger",
    "playful energy boost",
    "calming after-effect",
    "safe for all cats",
    "potent fresh leaves",
    "dried leaf preservation",
    "mild sedative qualities",
    "appetite stimulant",
    "social grooming trigger",
    "hunting instinct activator",
    "purr-inducing properties",
    "blissful contentment effect",
  ],
  cave: [
    "thrives without sunlight",
    "pale coloration",
    "sensitive to light",
    "draws nutrients from stone",
    "symbiotic with cave fauna",
    "extremely slow growth",
    "ancient specimens",
    "crystalline deposits",
    "moisture-dependent",
    "echo-location attractant",
    "mineral-rich tissues",
    "phosphorescent patches",
    "root system in rock cracks",
    "spore dispersal in darkness",
    "temperature stable",
  ],
  sacred: [
    "planted at temple founding",
    "centuries-old specimens",
    "meditation-enhancing presence",
    "incense-quality resin",
    "prayer bead seeds",
    "altar flower offerings",
    "purification smoke",
    "blessing ceremonies",
    "ancestor connection",
    "spiritual protection",
    "enlightenment symbolism",
    "monk-cultivated variety",
    "shrine maiden tended",
    "festival centerpiece",
    "pilgrimage destination",
  ],
  magical: [
    "fortune-telling properties",
    "dream-walking catalyst",
    "spirit-world glimpses",
    "fate-thread visibility",
    "prophecy enhancement",
    "luck manipulation",
    "time-sense alteration",
    "memory enhancement",
    "truth-revealing",
    "bond-strengthening",
    "weather prediction",
    "danger sensing",
    "healing acceleration",
    "creativity unlocking",
    "intuition sharpening",
  ],
};

// Use descriptions by type
export const USE_TEMPLATES = {
  food: [
    "Prepared as a staple ingredient in traditional dishes",
    "Served fresh in seasonal cuisine",
    "Dried and preserved for year-round use",
    "Used as a flavoring in soups and broths",
    "Pickled using ancestral techniques",
    "Ground into flour for baking",
    "Steeped as a nourishing tea",
    "Added to rice dishes for flavor and color",
    "Featured in festival celebrations",
    "Prized by guild chefs for its unique taste",
  ],
  medicine: [
    "Applied as a poultice for minor wounds",
    "Brewed into healing teas by temple healers",
    "Used in traditional remedies passed down through generations",
    "Prepared as a tincture by the Healer's Guild",
    "Combined with other herbs for enhanced effect",
    "Applied topically for skin conditions",
    "Taken internally for digestive wellness",
    "Used in steam treatments for respiratory health",
    "Featured in the Rare Garden's pharmacopeia",
    "Prescribed by village healers for common ailments",
  ],
  craft: [
    "Woven into decorative items by skilled artisans",
    "Carved into functional tools and utensils",
    "Used in traditional Whisker-Punk mechanisms",
    "Processed into durable fibers for textiles",
    "Shaped into containers and vessels",
    "Incorporated into ceremonial objects",
    "Utilized in furniture making by master craftscats",
    "Transformed into musical instruments",
    "Fashioned into jewelry and accessories",
    "Employed in architectural details",
  ],
  dye: [
    "Produces rich, lasting color for fabrics",
    "Used by the Artisan Union for textile dyeing",
    "Creates distinctive hues prized by tailors",
    "Combined with mordants for color fastness",
    "Traditional source of natural pigment",
    "Featured in ceremonial robe production",
    "Yields subtle, sophisticated tones",
    "Employed in paper-making for colored sheets",
    "Used in decorative painting",
    "Creates unique patterns through resist dyeing",
  ],
  decoration: [
    "Arranged in traditional ikebana displays",
    "Featured in seasonal garden designs",
    "Used to adorn homes during festivals",
    "Cultivated in temple gardens for contemplation",
    "Displayed in public spaces throughout the provinces",
    "Woven into celebratory garlands",
    "Featured in tea ceremony settings",
    "Used in wedding decorations",
    "Placed at shrines as offerings",
    "Arranged in tokonoma alcoves",
  ],
  ceremony: [
    "Central to seasonal festival observances",
    "Used in coming-of-age ceremonies",
    "Featured in memorial traditions",
    "Offered at ancestral shrines",
    "Part of guild initiation rituals",
    "Used in seasonal blessing ceremonies",
    "Featured in harvest thanksgiving",
    "Part of new year celebrations",
    "Used in purification rituals",
    "Central to meditation practices",
  ],
  "light-source": [
    "Harvested for natural illumination",
    "Used in traditional lantern making",
    "Provides ambient lighting for evening gatherings",
    "Featured in night market displays",
    "Used to light garden paths",
    "Incorporated into Whisker-Punk light fixtures",
    "Carried by travelers as portable light",
    "Used in theatrical productions",
    "Featured in romantic evening settings",
    "Placed along waterways for festivals",
  ],
  construction: [
    "Used in traditional building techniques",
    "Provides structural support in architecture",
    "Featured in roofing materials",
    "Used for interior wall finishing",
    "Processed into building boards",
    "Employed in bridge construction",
    "Used in boat building",
    "Featured in traditional fencing",
    "Used for scaffolding and temporary structures",
    "Processed into insulation materials",
  ],
  fragrance: [
    "Distilled into precious essential oils",
    "Used in incense production",
    "Featured in perfumery by skilled makers",
    "Dried and used in sachets",
    "Added to bathing waters",
    "Used in aromatherapy practices",
    "Featured in meditation spaces",
    "Burned in ceremonial censers",
    "Added to cosmetic preparations",
    "Used to scent storage spaces",
  ],
  fiber: [
    "Processed into durable rope",
    "Woven into traditional textiles",
    "Used in paper-making",
    "Featured in basket weaving",
    "Processed into fine cloth",
    "Used in net-making for fishing",
    "Featured in traditional sandal making",
    "Processed into stuffing materials",
    "Used in brush-making",
    "Woven into mats and floor coverings",
  ],
  euphoric: [
    "Provides safe, temporary euphoria for cats",
    "Used in play sessions to encourage activity",
    "Stuffed into toys for extended enjoyment",
    "Dried and stored for winter use",
    "Grown in personal gardens for daily access",
    "Shared during social gatherings",
    "Used to ease newcomer anxiety",
    "Featured in celebration ceremonies",
    "Applied to scratching posts and bedding",
    "Brewed into mild relaxation tea",
  ],
  spiritual: [
    "Burned as incense during meditation",
    "Offered at ancestral shrines",
    "Used in temple purification rituals",
    "Featured in coming-of-age ceremonies",
    "Planted to mark sacred boundaries",
    "Carried as blessing talismans",
    "Used in funeral rites",
    "Central to seasonal blessing ceremonies",
    "Cultivated by temple monks for generations",
    "Featured in pilgrimage traditions",
  ],
  magical: [
    "Consumed to enhance prophetic dreams",
    "Used in fortune-telling rituals",
    "Carried for luck and protection",
    "Brewed for memory enhancement",
    "Applied to reveal hidden truths",
    "Used in bonding ceremonies between cats",
    "Featured in weather-prediction rituals",
    "Consumed before important decisions",
    "Used to strengthen intuitive abilities",
    "Featured in creative inspiration rituals",
  ],
};

// Cultural associations
export const CULTURAL_ASSOCIATIONS = {
  positive: [
    "prosperity",
    "good fortune",
    "longevity",
    "wisdom",
    "peace",
    "harmony",
    "healing",
    "protection",
    "love",
    "friendship",
    "renewal",
    "hope",
    "courage",
    "patience",
    "gratitude",
  ],
  seasonal: [
    "spring awakening",
    "summer abundance",
    "autumn harvest",
    "winter rest",
    "cherry blossom season",
    "monsoon rains",
    "first frost",
    "new year",
    "midsummer",
    "harvest moon",
  ],
  spiritual: [
    "meditation",
    "contemplation",
    "ancestors",
    "nature spirits",
    "the Veil between worlds",
    "transformation",
    "rebirth",
    "inner peace",
    "enlightenment",
    "sacred space",
  ],
  social: [
    "community gatherings",
    "family bonds",
    "guild traditions",
    "welcoming newcomers",
    "mentorship",
    "celebration",
    "remembrance",
    "hospitality",
    "shared meals",
    "tea ceremony",
  ],
};

// Harvest cycles
export const HARVEST_CYCLES = [
  "annual, harvested in late summer",
  "perennial, producing for many seasons",
  "biennial, flowering in second year",
  "quick-growing, multiple harvests per season",
  "slow-maturing, requiring patient cultivation",
  "year-round availability with proper care",
  "seasonal fruiting in autumn",
  "spring harvest of tender shoots",
  "winter dormancy followed by spring growth",
  "continuous harvest through growing season",
];

// Cultivation requirements
export const CULTIVATION_REQUIREMENTS = {
  soil: [
    "rich, well-drained soil",
    "sandy coastal soil",
    "clay-heavy earth",
    "acidic forest floor",
    "alkaline mountain soil",
    "moist riverside loam",
    "rocky terrain with good drainage",
    "composted organic matter",
    "neutral pH garden beds",
    "mineral-rich volcanic soil",
  ],
  light: [
    "full sun exposure",
    "partial shade",
    "dappled forest light",
    "bright indirect light",
    "full shade",
    "morning sun, afternoon shade",
    "filtered light through canopy",
    "south-facing slopes",
    "protected from harsh midday sun",
    "minimal light requirements",
  ],
  water: [
    "regular watering",
    "drought tolerant once established",
    "constantly moist conditions",
    "periodic flooding",
    "minimal water needs",
    "misting for humidity",
    "deep but infrequent watering",
    "rainwater collection preferred",
    "standing water environment",
    "well-drained, never waterlogged",
  ],
  special: [
    "benefits from companion planting",
    "requires trellising for support",
    "needs winter protection in cold areas",
    "responds well to pruning",
    "self-seeding if conditions allow",
    "propagates easily from cuttings",
    "requires specific symbiotic fungi",
    "needs seasonal division",
    "benefits from mulching",
    "requires hand pollination in some areas",
  ],
};

// Guild connections
export const GUILD_CONNECTIONS = {
  "Healer's Guild": ["medicinal", "herb", "catnip", "sacred", "magical"],
  "Farmer's Collective": ["edible", "herb", "tree", "fruit", "catnip"],
  "Merchant's Guild": ["ornamental", "edible", "tree", "fruit", "catnip"],
  "Artisan Union": ["tree", "shrub", "herb", "fungi", "cave"],
  "Engineer's Guild": ["tree", "fungi", "glow-plant", "cave"],
  "Scholar's Circle": ["medicinal", "glow-plant", "fungi", "cave", "magical"],
  "Performance Guild": ["ornamental", "glow-plant", "sacred"],
};
